<template>
  <div class="home">
    <HelloWorld msg="CapMart"/>
    <img alt="An image of CapMart generated by the Wonderfully Amazing AI Software Imagine" src="../assets/95363562.jpg">
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue'
import HelloWorld from '@/components/HelloWorld.vue' // @ is an alias to /src

export default defineComponent({
  name: 'HomeView',
  components: {
    HelloWorld
  }
})
</script>

<style>
img {
  max-width: 100%;
  height: auto;
}
</style>
